### PR TITLE
feat: accept secret generator for verifyReceipt

### PR DESCRIPTION
**Pull request by sublimator**
re: https://github.com/interledgerjs/ilp-protocol-stream/issues/144

### CODE REVIEW

**Comment by sublimator** [comment]
@wilsonianb

**Comment by kincaidoneil** [comment]
Is it an issue if the generating the secret needed to be async, in which case the callback might not work?

(Alternatively, `verifyReceipt` could take the secret, raw receipt, and decoded receipt? The consumer would call `decodeReceipt`, optionally use their own logic to generate the secret, then call `verifyReceipt`)

**Comment by sublimator** [comment]
> Is it an issue if the generating the secret needed to be async
Yeah, I was pondering that, but then saw that the hmac verify operation was already sync. 
Also, this generally won't be used in the browser ( correct me if I'm wrong @wilsonianb ) and the node crypto library is generally sync (which always slightly surprised me) 

Having said all that, I'm generally in favor of async first apis these days for JS.

**Comment by sublimator** [comment]
@kincaidoneil 
If you have something better, go for it.  I just thought this was a practical/non breaking change.

**Comment by kincaidoneil** [comment]
> If you have something better, go for it. I just thought this was a practical/non breaking change.

Fair enough, I don't have strong opinions on it 👍

**Comment by sublimator** [comment]
awwww, never made it into 2.6.1 it seems
note that I can't actually merge this myself despite 2 approvals

**Comment by sharafian** [comment]
>  note that I can't actually merge this myself despite 2 approvals

I think that's because it requires a rebase

**Comment by sublimator** [comment]
@sharafian 
I rebased and pushed.
I think it's more due to the lack of permissions. 
I'm not down as a contributor to the repo or the parent org.

**Pull request merged**
