### PR TITLE
feat: add CreateConnectionOpts#unmanagedPlugin

### PR DESCRIPTION
**Pull request by sublimator**
re: https://github.com/interledger-rs/interledger-rs/issues/326#issuecomment-535899572

### CODE REVIEW

**Comment by sublimator** [comment]
@sentientwaffle

**Comment by sentientwaffle** [comment]
@sublimator Can you hold off on this PR for a couple days? I have a giant PR (the web crypto impl) that I'm working on & it will conflict with this one.

**Comment by sentientwaffle** [comment]
@sublimator: Rather than adding an option to ilp-protocol-stream, the caller could use a plugin wrapper that provides noop `connect`/`disconnect` and relays the other methods to the actual plugin.

**Comment by sublimator** [comment]
@sentientwaffle 
Yeah, it's not absolutely necessary, but I know of at least one other person that is currently creating a wrapper for the same purpose.

**Comment by sublimator** [comment]
https://github.com/Kava-Labs/ilp-sdk/blob/master/src/services/stream-server.ts#L44

**Pull request closed without merging**
